# Generated by Django 4.0.2 on 2022-07-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrainTumorSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date',
            new_name='dob',
        ),
    ]
